version: "3.8"

networks:
  seminario-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env                 
    environment:
      TZ: America/Argentina/Buenos_Aires
      UVICORN_PORT: 8000
    ports:
      - "127.0.0.1:8000:8000"  
    restart: unless-stopped
    networks: [seminario-network]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "127.0.0.1:8080:8080"  
    restart: unless-stopped
    depends_on: [backend]
    networks: [seminario-network]

